---
title: Canlis
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Canlis
global_nav:
- title: Menu
  slug: menu
- title: Our Story
  slug: story
- title: Wine
  slug: wine
- title: The Lounge
  slug: lounge
- title: Events
  slug: events
- title: Careers
  slug: careers
email: jeremy@jeremypbeasley.com
description: Seattle's landmark fine-dining destination for 70 years and recent home
  to multi-disciplinary pandemic pivots designed to serve our city.
og_title: Canlis, Seattle's storied restaurant.
og_photo: "/uploads/kevin.jpg"
dress_code: Go big. Dress up. Make a statement. You're beautiful, let it show! We
  are a dress-respectful restaurant. No casual or athletic attire please. Men will
  feel most comfortable in a suit or sport coat.
reservations_link: "/reservations"
baseurl: 
url: http://canlis.com
twitter_username: canlis
github_username: jeremypbeasley
markdown: kramdown
exclude:
- Gemfile.lock
- Gemfile
- Gruntfile.js
- node_modules
- package.json
- README.md
